name: My First Github Action
on: [push]
jobs:
  # print-hello-world:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Hello world!!!!"
  #     - run: echo "this is step number 2"

  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
